package com.flinkdsl.codegen;

import com.flinkdsl.ast.*;
import com.flinkdsl.ir.DataflowGraph;
import com.flinkdsl.ir.DataflowNode;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public class PipelineCodegen {

    private final DataflowGraph graph;
    private final Map<String, SchemaType> schema;
    private final ExprCodegen exprGen;
    private int streamIdx = 0;

    public PipelineCodegen(DataflowGraph graph) {
        this.graph = graph;

        Map<String, SchemaType> s = new LinkedHashMap<>();
        for (FieldDecl f : graph.source().schema()) {
            s.put(f.name(), f.type());
        }
        this.schema  = Collections.unmodifiableMap(s);
        this.exprGen = new ExprCodegen(schema);
    }

    public String generate() {
        String className = capitalize(graph.pipelineName()) + "Job";
        StringBuilder sb = new StringBuilder();

        emitImports(sb);
        sb.append("\n// Generated by Flink DSL Compiler\n");
        sb.append("public class ").append(className).append(" {\n\n");
        sb.append("    private static final ObjectMapper MAPPER = new ObjectMapper();\n\n");
        sb.append("    public static void main(String[] args) throws Exception {\n");
        sb.append("        StreamExecutionEnvironment env =\n");
        sb.append("                StreamExecutionEnvironment.getExecutionEnvironment();\n");
        sb.append("        env.setParallelism(").append(graph.parallelism()).append(");\n\n");

        String prevVar = null;
        for (DataflowNode node : graph.nodes()) {
            prevVar = emitNode(sb, node, prevVar);
        }

        sb.append("\n        env.execute(\"").append(graph.pipelineName()).append("\");\n");
        sb.append("    }\n}\n");
        return sb.toString();
    }

    private String emitNode(StringBuilder sb, DataflowNode node, String prevVar) {
        return switch (node) {
            case DataflowNode.Source  n -> emitSource(sb, n);
            case DataflowNode.Filter  n -> emitFilter(sb, n, prevVar);
            case DataflowNode.Map     n -> emitMap(sb, n, prevVar);
            case DataflowNode.FlatMap n -> emitFlatMap(sb, n, prevVar);
            case DataflowNode.Sink    n -> { emitSink(sb, n, prevVar); yield prevVar; }
        };
    }

    private String emitSource(StringBuilder sb, DataflowNode.Source node) {
        String var = node.streamName();
        sb.append("        // ── ").append(node.id()).append("\n");

        switch (node.connector()) {
            case ConnectorNode.KafkaConnector c -> {
                sb.append("        KafkaSource<String> kafkaSource = KafkaSource.<String>builder()\n");
                sb.append("                .setTopics(\"").append(c.topic()).append("\")\n");
                sb.append("                .setValueOnlyDeserializer(new SimpleStringSchema())\n");
                sb.append("                .setStartingOffsets(OffsetsInitializer.earliest())\n");
                sb.append("                .build();\n");
                sb.append("        DataStream<ObjectNode> ").append(var).append(" = env\n");
                sb.append("                .fromSource(kafkaSource, WatermarkStrategy.noWatermarks(), \"")
                  .append(node.id()).append("\")\n");
                sb.append("                .map(json -> MAPPER.readValue(json, ObjectNode.class));\n\n");
            }
            case ConnectorNode.FileConnector c -> {
                sb.append("        DataStream<ObjectNode> ").append(var).append(" = env\n");
                sb.append("                .readTextFile(\"").append(c.path()).append("\")\n");
                sb.append("                .map(line -> MAPPER.readValue(line, ObjectNode.class));\n\n");
            }
        }
        return var;
    }

    private String emitFilter(StringBuilder sb, DataflowNode.Filter node, String prevVar) {
        String var = nextVar();
        sb.append("        // ── ").append(node.id()).append("\n");
        sb.append("        DataStream<ObjectNode> ").append(var)
          .append(" = ").append(prevVar).append(".filter(\n");
        sb.append("                record -> ").append(exprGen.generate(node.predicate())).append(");\n\n");
        return var;
    }

    private String emitMap(StringBuilder sb, DataflowNode.Map node, String prevVar) {
        String var = nextVar();
        sb.append("        // ── ").append(node.id()).append("\n");
        sb.append("        DataStream<ObjectNode> ").append(var)
          .append(" = ").append(prevVar).append(".map(record -> {\n");
        sb.append("            ObjectNode out = MAPPER.createObjectNode();\n");
        for (FieldAssignment a : node.assignments()) {
            sb.append("            out.put(\"").append(a.field()).append("\", ")
              .append(exprGen.generate(a.value())).append(");\n");
        }
        sb.append("            return out;\n");
        sb.append("        });\n\n");
        return var;
    }

    private String emitFlatMap(StringBuilder sb, DataflowNode.FlatMap node, String prevVar) {
        String var = nextVar();
        sb.append("        // ── ").append(node.id()).append("\n");
        sb.append("        DataStream<ObjectNode> ").append(var)
          .append(" = ").append(prevVar).append(".flatMap(\n");
        sb.append("                new FlatMapFunction<ObjectNode, ObjectNode>() {\n");
        sb.append("                    @Override\n");
        sb.append("                    public void flatMap(ObjectNode record,\n");
        sb.append("                                       Collector<ObjectNode> out) throws Exception {\n");
        sb.append("                        ObjectNode result = MAPPER.createObjectNode();\n");
        for (FieldAssignment a : node.assignments()) {
            sb.append("                        result.put(\"").append(a.field()).append("\", ")
              .append(exprGen.generate(a.value())).append(");\n");
        }
        sb.append("                        out.collect(result);\n");
        sb.append("                    }\n");
        sb.append("                });\n\n");
        return var;
    }

    private void emitSink(StringBuilder sb, DataflowNode.Sink node, String prevVar) {
        sb.append("        // ── ").append(node.id()).append("\n");

        switch (node.connector()) {
            case ConnectorNode.KafkaConnector c -> {
                sb.append("        KafkaSink<String> kafkaSink = KafkaSink.<String>builder()\n");
                sb.append("                .setRecordSerializer(\n");
                sb.append("                        KafkaRecordSerializationSchema.builder()\n");
                sb.append("                                .setTopic(\"").append(c.topic()).append("\")\n");
                sb.append("                                .setValueSerializationSchema(new SimpleStringSchema())\n");
                sb.append("                                .build())\n");
                sb.append("                .build();\n");
                sb.append("        ").append(prevVar)
                  .append(".map(n -> MAPPER.writeValueAsString(n)).sinkTo(kafkaSink);\n");
            }
            case ConnectorNode.FileConnector c -> {
                sb.append("        FileSink<String> fileSink = FileSink\n");
                sb.append("                .<String>forRowFormat(\n");
                sb.append("                        new Path(\"").append(c.path()).append("\"),\n");
                sb.append("                        new SimpleStringEncoder<>(\"UTF-8\"))\n");
                sb.append("                .build();\n");
                sb.append("        ").append(prevVar)
                  .append(".map(n -> MAPPER.writeValueAsString(n)).sinkTo(fileSink);\n");
            }
        }
    }

    private String nextVar() { return "s" + (streamIdx++); }

    static String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private void emitImports(StringBuilder sb) {
        sb.append("import com.fasterxml.jackson.databind.ObjectMapper;\n");
        sb.append("import com.fasterxml.jackson.databind.node.ObjectNode;\n");
        sb.append("import org.apache.flink.api.common.eventtime.WatermarkStrategy;\n");
        sb.append("import org.apache.flink.api.common.functions.FlatMapFunction;\n");
        sb.append("import org.apache.flink.api.common.serialization.SimpleStringEncoder;\n");
        sb.append("import org.apache.flink.api.common.serialization.SimpleStringSchema;\n");
        sb.append("import org.apache.flink.connector.file.sink.FileSink;\n");
        sb.append("import org.apache.flink.connector.kafka.sink.KafkaRecordSerializationSchema;\n");
        sb.append("import org.apache.flink.connector.kafka.sink.KafkaSink;\n");
        sb.append("import org.apache.flink.connector.kafka.source.KafkaSource;\n");
        sb.append("import org.apache.flink.connector.kafka.source.enumerator.initializer.OffsetsInitializer;\n");
        sb.append("import org.apache.flink.core.fs.Path;\n");
        sb.append("import org.apache.flink.streaming.api.datastream.DataStream;\n");
        sb.append("import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;\n");
        sb.append("import org.apache.flink.util.Collector;\n");
    }
}
